FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Academy

Polls is a simple API allowing consumers to view polls and vote in them.


## User Related [/UserProfile/{userGuId}/{languageId}]
### getUserProfile [GET]

This API is use for to get User Profile on the basis of userid,AuthenticationToken,languageId
+ Request

        + Header (application/json)
            {   
                "Content-Type":"application/json",
                "authenticationToken":"58sa36sd214897SA1246er"
            }

+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    
+ Response 200 (application/json)

    + Body

            {
                "Id": 1,
                "Name": "Niraj Sharma",
                "Role": "Guest",
                "Status": "Hiker",
                "ProfilePercent": 11,
                "CourcePercent": 22,
                "TestScorePercent": 33,
                "UserGuid": "2ds5r53as5r8v65ae78795661"
            }
            
+ Response 400 (application/json)
  + Body

            {
                "Error": "Error"
            }
            
## Item Related [/Items/{userGuId}/{languageId}]
### GetItems [GET]
This API is use for to get all items on the basis of userid,AuthenticationToken,languageId


+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
            
+ Response 200 (application/json)

    + Body
        
            [
              {
                "ItemId": "ItemId1",
                "ItemGuid": "ItemGuid1",
                "ItemTitle": "ItemTitle1",
                "ItemStatus": "ItemStatus1"
              },
              {
                "ItemId": "ItemId2",
                "ItemGuid": "ItemGuid2",
                "ItemTitle": "ItemTitle2",
                "ItemStatus": "ItemStatus2"
              }
            ]

## Location Related [/AllLocation/{userGuId}/{languageId}]
### getAllLocation [GET]

This API is use for to get all location on the basis of authenticationToken.

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    
+ Response 200 (application/json)


    + Body

            [
                {
                "Id": "1",
                "Name": "US"
                },
                {
                "Id": "2",
                "Name": "UK"
                }
            ]

## Track Related [/Track/{userGuId}/{languageId}]
### getTrack [GET]

This API is use for to get all Track on the basis of userid,AuthenticationToken,languageId

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    
+ Response 200 (application/json)


    + Body
    
            [
                {
                    "TrackId": 1,
                    "TrackGuid": "dsa2432fvf3c3c3c3gv3g",
                    "TrackTitle": "TrackTitle",
                    "TrackDescription": "TrackDescription"
                },
                {
                    "TrackId": 2,
                    "TrackGuid": "zq45srer54554xaqz21585",
                    "TrackTitle": "TrackTitle2",
                    "TrackDescription": "TrackDescription"
                }
            ]           
            
## Course Related [/Courses/{userGuId}/{languageId}/{TrackGuId}]
### getCourses [GET]

This API is use for to get all courses on the basis of userid,AuthenticationToken,languageId,TrackGuid

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    + TrackGuId - zq45srer54554xaqz21585


+ Response 200 (application/json)


    + Body
    
            [
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid",
                    "CourseTitle": "CourseTitle",
                    "CourseDescription": "CourseDescription"
                },
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid2",
                    "CourseTitle": "CourseTitle2",
                    "CourseDescription": "CourseDescription"
                }
            ]           
        
## Unit Related [/Unit/{userGuId}/{languageId}/{TrackGuId}/{CourseGuid}]
### getUnit [GET]

This API is use for to get all unit on the basis of userid,AuthenticationToken,languageId,TrackGuid,CourseGuid
+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    + TrackGuId - zq45srer54554xaqz21585
    + CourseGuid - zaaxsa2313216s6fd4s64s

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "UnitId": "UnitId",
                    "UnitGuid": "UnitGuid",
                    "UnitTitle": "UnitTitle"
                }
            ]