FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Academy

Polls is a simple API allowing consumers to view polls and vote in them.


## User Related [/userprofile]
### getUserProfile [POST]

This API is use for to get User Profile on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        +Header (application/json)
            {   
                "access-control-allow-methods":"OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT",
                "Content-Type":"application/json",
                "authenticationToken":"58sa36sd214897SA1246er"
            }

        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1
            }
                        
+ Response 200 (application/json)

    + Body

            {
                "UserId": "1",
                "UserName": "Sanchit",
                "UserProfileRole": "Guest",
                "UserProfileStatus": "Hiker",
                "UserProfilePercent": 11
            }
            
+ Response 400 (application/json)
  + Body

            {
                "Error": "Error"
            }
            
## Item Related [/Items/{userGuId}/{languageId}]
### GetItems [GET]
This API is use for to get all items on the basis of userid,AuthenticationToken,languageId


+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
            
+ Response 200 (application/json)

    + Body
        
            [
              {
                "ItemId": "ItemId1",
                "ItemGuid": "ItemGuid1",
                "ItemTitle": "ItemTitle1",
                "ItemStatus": "ItemStatus1"
              },
              {
                "ItemId": "ItemId2",
                "ItemGuid": "ItemGuid2",
                "ItemTitle": "ItemTitle2",
                "ItemStatus": "ItemStatus2"
              }
            ]

## Location Related [/AllLocation/{userGuId}/{languageId}]
### getAllLocation [GET]

This API is use for to get all location on the basis of authenticationToken.

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    
+ Response 200 (application/json)


    + Body

            [
                {
                "Id": "1",
                "Name": "US"
                },
                {
                "Id": "2",
                "Name": "UK"
                }
            ]

## Track Related [/track]
### getTrack [POST]

This API is use for to get all Track on the basis of userid,AuthenticationToken,languageId

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1
            }
    
+ Response 200 (application/json)


    + Body
    
            [
                {
                    "TrackId": 1,
                    "TrackGuid": "dsa2432fvf3c3c3c3gv3g",
                    "TrackTitle": "TrackTitle",
                    "TrackDescription": "TrackDescription"
                },
                {
                    "TrackId": 2,
                    "TrackGuid": "zq45srer54554xaqz21585",
                    "TrackTitle": "TrackTitle2",
                    "TrackDescription": "TrackDescription"
                }
            ]           
            
## Course Related [/courses]
### getCourses [POST]

This API is use for to get all courses on the basis of userid,AuthenticationToken,languageId,TrackGuid

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
                }
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1,
                "trackGuId": "zq45srer54554xaqz21585"
            }

+ Response 200 (application/json)


    + Body
    
            [
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid",
                    "CourseTitle": "CourseTitle11",
                    "CourseDescription": "CourseDescription"
                },
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid2",
                    "CourseTitle": "CourseTitle22",
                    "CourseDescription": "CourseDescription"
                }
            ]           
        
## Unit Related [/Unit]
### getUnit [GET]

This API is use for to get all unit on the basis of userid,AuthenticationToken,languageId,TrackGuid,CourseGuid
+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
                
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1,
                "trackGuId": "zq45srer54554xaqz21585",
                "courseGuid":"zaaxsa2313216s6fd4s64s"
            }


+ Response 200 (application/json)

    + Body
    
            [
                {
                    "UnitId": "UnitId",
                    "UnitGuid": "UnitGuid",
                    "UnitTitle": "UnitTitle"
                }
            ]

## Course Related [/userprofile/coursecompleted]
### getCoursePercent [POST]

This API is use for to get User Profile Course Completion Percent on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1
            }
  
+ Response 200 (application/json)

    + Body
    
            
            {
                    "UserProfileCoursePercent": 22
            }
                        
## Score Related [/userprofile/scorecompleted]
### getScorePercent [POST]

This API is use for to get User Profile Score Percent on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1
            }
+ Response 200 (application/json)

    + Body
    
            {
                    "UserProfileTestScorePercent": 33
            }