FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Academy

Polls is a simple API allowing consumers to view polls and vote in them.


## User Profile Related [/userprofile]
### getUserProfile [POST]

This API is use for to get User Profile on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        +Header (application/json)
            {   
                "access-control-allow-methods":"OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT",
                "Content-Type":"application/json",
                "authenticationToken":"58sa36sd214897SA1246er"
            }

        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1
            }
                        
+ Response 200 (application/json)

    + Body

            {
                "UserId": "1",
                "UserName": "Sanchit",
                "UserProfileRole": "Guest",
                "UserProfileStatus": "Hiker",
                "UserProfilePercent": 11
            }
            
+ Response 400 (application/json)
  + Body

            {
                "Error": "Error"
            }
            
## My Learning Journey Related [/item]
### GetItems [POST]
This API is use for to get all items on the basis of userid,AuthenticationToken,languageId


+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1,
                "trackGuId": "zq45srer54554xaqz21585",
                "courseGuid":"zaaxsa2313216s6fd4s64s",
                "unitGuid":"58sa36sd214897SA1246er"
            }
            
+ Response 200 (application/json)

    + Body
        
            [
              {
                "ItemId": "ItemId1",
                "ItemGuid": "ItemGuid1",
                "ItemTitle": "ItemTitle1",
                "ItemStatus": "1",
                "ItemType":6,
                "ItemTypeIconImage":"Video_In_Progress.png",
                "ItemTypeStatusImage":"item_running.png"
              },
              {
                "ItemId": "ItemId23",
                "ItemGuid": "ItemGuid2",
                "ItemTitle": "ItemTitle2",
                "ItemStatus": "0",
                "ItemType":1,
                "ItemTypeIconImage":"elearning.png",
                "ItemTypeStatusImage":"item_assigned.png"
              },
              {
                "ItemId": "ItemId23",
                "ItemGuid": "ItemGuid2",
                "ItemTitle": "ItemTitle2 This API is use for to get all items",
                "ItemStatus": "2",
                "ItemType":1,
                "ItemTypeIconImage":"elearning.png",
                "ItemTypeStatusImage":"item_completed.png"
              }
            ]

## Location Related [/AllLocation/{userGuId}/{languageId}]
### getAllLocation [GET]

This API is use for to get all location on the basis of authenticationToken.

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
+ Parameters
    + userGuId - 2ds5r53as5r8v65ae78795661
    + languageId - 1
    
+ Response 200 (application/json)


    + Body

            [
                {
                "Id": "1",
                "Name": "US"
                },
                {
                "Id": "2",
                "Name": "UK"
                }
            ]

## My Learning Journey Related [/track]
### getTrack [POST]

This API is use for to get all Track on the basis of userid,AuthenticationToken,languageId

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1
            }
    
+ Response 200 (application/json)


    + Body
    
            [
                {
                    "TrackId": 1,
                    "TrackGuid": "dsa2432fvf3c3c3c3gv3g",
                    "TrackTitle": "TrackTitle Polls is a simple API allowing consumers to",
                    "TrackDescription": "TrackDescription"
                },
                {
                    "TrackId": 2,
                    "TrackGuid": "zq45srer54554xaqz21585",
                    "TrackTitle": "TrackTitle2",
                    "TrackDescription": "TrackDescription"
                }
            ]           
            
## My Learning Journey Related [/courses]
### getCourses [POST]

This API is use for to get all courses on the basis of userid,AuthenticationToken,languageId,TrackGuid

+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
                }
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1,
                "trackGuId": "zq45srer54554xaqz21585"
            }

+ Response 200 (application/json)


    + Body
    
            [
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid",
                    "CourseTitle": "Polls is a simple API allowing consumers to",
                    "CourseDescription": "CourseDescription"
                },
                {
                    "CourseId": "CourseId",
                    "CourseGuid": "CourseGuid2",
                    "CourseTitle": "CourseTitle22",
                    "CourseDescription": "CourseDescription"
                }
            ]           
        
## My Learning Journey Related [/unit]
### getUnit [POST]

This API is use for to get all unit on the basis of userid,AuthenticationToken,languageId,TrackGuid,CourseGuid
+ Request ()

            + Header (application/json)
                {
                    "authenticationToken":"58sa36sd214897SA1246er"
                }
                
        + body
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId": 1,
                "trackGuId": "zq45srer54554xaqz21585",
                "courseGuid":"zaaxsa2313216s6fd4s64s"
            }


+ Response 200 (application/json)

    + Body
    
            [
                {
                    "UnitId": "UnitId",
                    "UnitGuid": "UnitGuid",
                    "UnitTitle": "UnitTitle Polls is a simple API allowing consumers to"
                }
            ]

## User Profile Course Score Related [/userprofile/coursecompleted]
### getCoursePercent [POST]

This API is use for to get User Profile Course Completion Percent on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1
            }
  
+ Response 200 (application/json)

    + Body
    
            
            {
                    "UserProfileCoursePercent": 22
            }
                        
## User Profile Track Score Related [/userprofile/scorecompleted]
### getScorePercent [POST]

This API is use for to get User Profile Score Percent on the basis of userid,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1
            }
+ Response 200 (application/json)

    + Body
    
            {
                    "UserProfileTestScorePercent": 33
            }
            
            
## Right Panel  Related [/userdetails/itemdetail]
### getItemDetailbyId [POST]

This API is use for to get item detail  on the basis of userGuId,AuthenticationToken,languageId,TopicItemGuid
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1,
                "TopicItemGuid" : "Topic1GUID"
            }
+ Response 200 (application/json)

    + Body
    
            {
                    "TopicItemId": 1,
                    "TopicItemTitle":"Topic1",
                    "TopicItemVideoUrl":"Topic1TopicItemVideoUrl",
                    "TopicItemDuration":20,
                    "TopicItemGuid":"Topic1GUID",
                    "ItemStarted":true,
                    "TopicItemStatus":"1",
                    "TopicItemType":6
                    
            }
            
            
## Right Panel  Related [/userdetails/itemrating]
### getItemRatingbyId [POST]

This API is use for to get Rating of particaular Item  on the basis of userGuId,AuthenticationToken,languageId,TopicItemGuid
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1,
                "TopicItemGuid" : "Topic1GUID"
            }
+ Response 200 (application/json)

    + Body
    
            {
                    "TopicItemId": 1,
                    "TopicItemGuid":"Topic1GUID",
                    "TopicItemRating":3
                    }
                    

## Right Panel  Related [/userdetails/itemcheckbookmark]
### getItemBookmarkbyId [POST]

This API is use for to check whether item is bookmark or nor on the basis of userGuId,AuthenticationToken,languageId,TopicItemGuid
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1,
                "TopicItemGuid" : "Topic1GUID"
            }
+ Response 200 (application/json)

    + Body
    
            {
                    "TopicItemId": 1,
                    "TopicItemGuid":"Topic1GUID",
                    "TopicItemIsBookmarked":true
             }                    
                    

## Test Item Related [/userdetails/testitems]
### gettestItem [POST]

This API is use for to get All Test on the basis of UnitId,userGuId,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1,
                "UnitGuId" : "UnitGUID"
            }
+ Response 200 (application/json)

    + Body
    
               [ 
               {
                    "TestItemId": 1,
                    "TestItemGuid":"ItemGuid1",
                    "TestItemTitle":"API Quiz Contest - Test 1",
                    "TestItemMaxScore": 200,
                    "TestItemAttempts":10,
                    "TestTotalAttempts":25,
                    "TestItemStatus":1
                }
                ]
                
                
## Right Panel  Related [/newlearning/newlearningitem]
### getnewLearningItem [POST]

This API is use for to get New LearningItem for User on the basis of userGuid,AuthenticationToken,languageId
+ Request (application/json)

        + Header (application/json)
            {
                "authenticationToken":"58sa36sd214897SA1246er"
            }
        + Body
            
            {
                "userGuId": "2ds5r53as5r8v65ae78795661",
                "languageId" : 1,
               
            }
+ Response 200 (application/json)

    + Body
    
               [ 
               {
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title1",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-1.png",
                    "ItemDuration":20
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title2",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-2.png",
                    "ItemDuration":10
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title3",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-1.png",
                    "ItemDuration":30
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title4",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-2.png",
                    "ItemDuration":45
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title1",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-1.png",
                    "ItemDuration":20
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title2",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-2.png",
                    "ItemDuration":10
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title3",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-1.png",
                    "ItemDuration":30
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title4",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-2.png",
                    "ItemDuration":45
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title3",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-1.png",
                    "ItemDuration":30
                },{
                    "ItemId": 1,
                    "ItemGuid":"ItemGuid1",
                    "ItemTitle":"API Item Title4",
                    "ItemStatus": "ItemStatus",
                    "ItemDescription":"ItemDescription",
                    "Imagepath":"images/image-2.png",
                    "ItemDuration":45
                }
                ]